spring:
  application:
    name: spring-boot-refresh-token
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_api
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl_auto: none
    show-sql: false
    open-in-view: false

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
  server:
    url: http://localhost:8080