CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(25) NOT NULL,
    username character varying(25) NOT NULL,
    password character varying(255) NOT NULL
);

ALTER TABLE public.users OWNER TO admin;

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

COPY public.users (id, email, username, password) FROM stdin;
\.

SELECT pg_catalog.setval('public.users_id_seq', 1, false);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);